name: tesla_extension
version: 0.0.1
dependencies:
  angular: 0.10.0
  browser: any
  js: any
  google_maps: ">=2.0.0 <3.0.0"
dev_dependencies:
  unittest: any
transformers:
- angular:
    html_files:
    - web/view/charge.html
    - web/view/climate.html
    - web/view/controls.html
    - web/view/home.html
    - web/view/location.html